apiVersion : apps/v1
kind: Deployment
metadata:
  name: jagdevorgazurespringbootpoc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jagdevorgazurespringbootpoc
  template:
    metadata:
      labels:
        app: jagdevorgazurespringbootpoc 
    spec:
      containers:
        - name: jagdevorgazurespringbootpoc 
          image: mydemoacrrepo001.azurecr.io/Ajit120708/dockerspringbootpocnew:27
          ports:
          - containerPort: 8080
